const items = [
  // {
  //   id: 1,
  //   title: "Game of life",
  //   category: "C",
  //   img: "./img/works/game_of_life2.png",
  //   link: "https://github.com/proksims/Profil",
  //   git: "git_white",
  // },
  {
    id: 2,
    title: "Math",
    category: "C",
    img: "./img/works/math.png",
    link: "https://github.com/proksims/Math",
    git: "git_white",
  },
  {
    id: 3,
    title: "Decimal",
    category: "C",
    img: "./img/works/dec.jpg",
    link: "https://github.com/proksims/Decimal",
    git: "git_white",
  },
  {
    id: 4,
    title: "Bash Utils",
    category: "C",
    img: "./img/works/grep.png",
    link: "https://github.com/proksims/Bash_Utils",
    git: "git_white",
  },
  {
    id: 5,
    title: "Library string.h",
    category: "C",
    img: "./img/works/printf-and-scanf.png",
    link: "https://github.com/proksims/String",
    git: "git_white",
  },
  {
    id: 6,
    title: "Library containers.h",
    category: "C++",
    img: "./img/works/stl.png",
    link: "https://github.com/proksims/Containers",
    git: "git_dark",
  },
  {
    id: 7,
    title: "Matrix",
    category: "C/C++",
    img: "./img/works/matrix.jpg",
    link: "https://github.com/proksims/Matrix",
    git: "git_white",
  },
  {
    id: 8,
    title: "Calculator",
    category: "C/C++",
    img: "./img/works/calc.png",
    link: "https://github.com/proksims/Calculator",
    git: "git_white",
  },
  {
    id: 9,
    title: "3D Viewer",
    category: "C/C++",
    img: "./img/works/3d.png",
    link: "https://github.com/proksims/3D_Viewer",
    git: "git_white",
  },
  {
    id: 10,
    title: "Linux projects",
    category: "Linux",
    img: "./img/works/linux.png",
    link: "https://github.com/proksims/Linux_projects",
    git: "git_white",
  },
  // {
  //   id: 11,
  //   title: "Intensive SQL",
  //   category: "SQL",
  //   img: "./img/works/sql.png",
  //   link: "#",
  // },
  // {
  //   id: 12,
  //   title: "Algorithms JS",
  //   category: "JS",
  //   img: "./img/works/js.jpeg",
  //   link: "#",
  //   git: "git_white",
  // },
  // {
  //   id: 13,
  //   title: "ToDo List",
  //   category: "JS",
  //   img: "./img/works/todo.png",
  //   link: "#",
  //   git: "none",
  // },
];
