const items = [
  {
    id: 14,
    title: "SVG Animation",
    category: "JS",
    category_main: "JS",
    img: "./img/works/svg.png",
    par: "Work with SVG and animation.",
    link_git: "https://github.com/proksims/SVG_Animation",
    site: "#",
    link_site: "https://proksims.github.io/SVG_Animation/",
    git: "git_dark",
    filter: 'filter',
  },
  {
    id: 13,
    title: "Game: Game of life",
    category: "JS",
    category_main: "JS",
    img: "./img/works/game_of_life2.png",
    par: "Game of life with p5*js library. Work with canvas.",
    link_git: "https://github.com/proksims/Game_of_Life",
    site: "#",
    link_site: "https://proksims.github.io/Game_of_Life/",
    git: "git_dark",
    filter: 'filter',
  },

  {
    id: 12,
    title: "Game: Rock Paper Scissors",
    category: "JS",
    category_main: "JS",
    img: "./img/works/rock.png",
    par: "Rock paper scissors game with score counting against computer.",
    link_git: "https://github.com/proksims/Rock_paper_scissors",
    site: "#",
    link_site: "https://proksims.github.io/Rock_paper_scissors/",
    git: "git_dark",
    filter: 'filter',
  },

  {
    id: 15,
    title: "SVG in Adobe Illustrator",
    category: "JS",
    category_main: "JS",
    img: "./img/works/svg_ad.png",
    par: "Made SVG in Adobe Illustrator.",
    link_git: "https://github.com/proksims/SVG_Adobe_Illustrator",
    site: "#",
    link_site: "https://proksims.github.io/SVG_Adobe_Illustrator/",
    git: "git_dark",
    filter: '',
  },

  {
    id: 11,
    title: "ToDo List",
    category: "JS",
    category_main: "JS",
    img: "./img/works/todo.png",
    par: "List of tasks with the ability to complete and delete tasks.",
    link_git: "https://github.com/proksims/ToDo_List",
    site: "#",
    link_site: "https://proksims.github.io/ToDo_List/",
    git: "git_dark",
    filter: 'filter',
  },



  {
    id: 2,
    title: "Library math.h",
    category: "C/C++",
    category_main: "C",
    img: "./img/works/math.png",
    filter: '',     // color for img dark mode
    par: "Implementation of the math.h library.",
    link_git: "https://github.com/proksims/Math",
    git: "git_white",     // color for git icon on img
    site: "none",
    link_site: "",
  },
  {
    id: 3,
    title: "Library decimal.h",
    category: "C/C++",
    category_main: "C",
    img: "./img/works/dec.jpg",
    par: "Implementation of the decimal.h library.",
    link_git: "https://github.com/proksims/Decimal",
    site: "none",
    link_site: "",
    git: "git_white",
    filter: '',
  },
  {
    id: 4,
    title: "Library string.h",
    category: "C/C++",
    category_main: "C",
    img: "./img/works/printf-and-scanf.png",
    par: "Implementation of the string.h library.",
    link_git: "https://github.com/proksims/String",
    site: "none",
    link_site: "",
    git: "git_white",
    filter: '',
  },
  {
    id: 5,
    title: "Bash Utils",
    category: "Linux",
    category_main: "Linux",
    img: "./img/works/grep.png",
    par: "Development of Bash text utilities: cat, grep; in the C programming language.",
    link_git: "https://github.com/proksims/Bash_Utils",
    site: "none",
    link_site: "",
    git: "git_white",
    filter: '',
  },

  {
    id: 6,
    title: "Library containers.h",
    category: "C/C++",
    category_main: "C++",
    img: "./img/works/stl.png",
    par: "Implement the library, that implements the basic standard C++ container classes.",
    link_git: "https://github.com/proksims/Containers",
    site: "none",
    link_site: "",
    git: "git_dark",
    filter: '',
  },
  {
    id: 7,
    title: "Matrix",
    category: "C/C++",
    category_main: "C/C++",
    img: "./img/works/matrix.jpg",
    par: "Implement library for processing numerical matrices.",
    link_git: "https://github.com/proksims/Matrix",
    site: "none",
    link_site: "",
    git: "git_white",
    filter: '',
  },

  {
    id: 8,
    title: "Calculator",
    category: "C/C++",
    category_main: "C/C++",
    img: "./img/works/calc.webp",
    par: "Implement an extended version of the usual calculator.",
    link_git: "https://github.com/proksims/Calculator",
    site: "none",
    link_site: "",
    git: "git_white",
    filter: '',
  },
  {
    id: 9,
    title: "3D Viewer",
    category: "C/C++",
    category_main: "C/C++",
    img: "./img/works/3d.png",
    par: "Implement a program to view 3D wireframe models (MVC pattern).",
    link_git: "https://github.com/proksims/3D_Viewer",
    site: "none",
    link_site: "",
    git: "git_white",
    filter: '',
  },
  {
    id: 10,
    title: "Linux projects",
    category: "Linux",
    category_main: "Linux",
    // img: "./img/works/linux.png",
    img: "./img/works/bash.jpg",
    par: "Administration basics. Linux networks configuration on virtual machines. Bash scripting. Docker.",
    link_git: "https://github.com/proksims/Linux_projects",
    site: "none",
    link_site: "",
    git: "git_white",
    filter: '',
  },

  // {
  //   id: 13,
  //   title: "Intensive SQL",
  //   category: "SQL",
  //   img: "./img/works/sql.png",
  //   link_git: "#",
  // },
  // {
  //   id: 14,
  //   title: "Algorithms JS",
  //   category: "JS",
  //   img: "./img/works/js.jpeg",
  //   link_git: "#",
  //   site: "none",
  // },
];
